---
apiVersion: v1
kind: Service
metadata:
  name: payments
  namespace: default
spec:
  selector:
    app: payments
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: payments
  namespace: default
automountServiceAccountToken: true
---
apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceDefaults
metadata:
  name: payments
  namespace: default
spec:
  protocol: "http"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: payments
  namespace: default
  labels:
    app: payments
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payments
  template:
    metadata:
      labels:
        app: payments
      annotations:
        #prometheus.io/scrape: "true"
        #prometheus.io/port: "9102"
        consul.hashicorp.com/connect-inject: "true"
        sidecar.opentelemetry.io/inject: "true"
        consul.hashicorp.com/enable-metrics-merging: "true"
        consul.hashicorp.com/service-metrics-port: "8080"
        consul.hashicorp.com/service-metrics-path: "/actuator/prometheus"
    spec:
      serviceAccountName: payments
      containers:
        - name: payments
          image: hashicorpdemoapp/payments:v0.0.16
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
        - name: jaeger-agent
          image: jaegertracing/jaeger-agent:latest
          imagePullPolicy: IfNotPresent
          ports:
          - containerPort: 5775
            name: zk-compact-trft
            protocol: UDP
          - containerPort: 5778
            name: config-rest
            protocol: TCP
          - containerPort: 6831
            name: jg-compact-trft
            protocol: UDP
          - containerPort: 6832
            name: jg-binary-trft
            protocol: UDP
          - containerPort: 14271
            name: admin-http
            protocol: TCP
          args:
          - --reporter.grpc.host-port=dns:///simplest-collector.default.svc.cluster.local:14250
          - --reporter.type=grpc