# Copyright (c) HashiCorp, Inc.
# SPDX-License-Identifier: MPL-2.0

global:
  name: consul
  datacenter: dc1
server:
  replicas: 1
connectInject:
  enabled: true
  default: true
controller:
  enabled: true