# Copyright (c) HashiCorp, Inc.
# SPDX-License-Identifier: MPL-2.0

---
global:
  scrape_interval:  5s
  scrape_timeout: 3s

server:
  persistentVolume:
    enabled: false

alertmanager:
  enabled: false
