apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
metadata:
  name: sidecar-for-my-app
spec:
  mode: sidecar
  config: |
    receivers:
      prometheus:
        config:
          scrape_configs:
            - job_name: "otel-collector"
              scrape_interval: 5s
              static_configs:
                - targets: ["localhost:9102"]
      jaeger:
        protocols:
          grpc:
          thrift_binary:
          thrift_compact:
          thrift_http:
    exporters:
      prometheus: 
        endpoint: "loki-prometheus-server.default.svc.cluster.local:80"
        namespace: "default"
      #loki:
        #endpoint: "loki-collector.default.svc.cluster.local:1234"
      jaeger:
        endpoint: "simplest-collector.default.svc.cluster.local:14250"
        tls:
          insecure: true
    processors:
    service:
      pipelines:
        metrics:
          receivers: [prometheus]
          processors: []
          exporters: [prometheus]
        traces:
          receivers: [jaeger]
          processors: []
          exporters: [jaeger]