global:
  enabled: true
  name: consul
  datacenter: dc1
  metrics:
    enabled: true
    enableAgentMetrics: true
    agentMetricsRetentionTime: "1m"
server:
  replicas: 1
ui:
  enabled: true
  metrics:
    enabled: true
    provider: "prometheus"
    baseURL: http://prometheus-server.default.svc.cluster.local
connectInject:
  enabled: true
  default: true
  metrics:
    defaultPrometheusScrapePort: 20200
    defaultPrometheusScrapePath: "/metrics"
controller:
  enabled: true
#centralConfig:
#  enabled: true

  # defaultProtocol allows you to specify a convenience default protocol if
  # most of your services are of the same protocol type. The individual annotation
  # on any given pod will override this value. A protocol must be provided,
  # either through this setting or individual annotation, for a service to be
  # registered correctly. Valid values are "http", "http2", "grpc" and "tcp".
#  defaultProtocol: null

  # proxyDefaults is a raw json string that will be applied to all Connect
  # proxy sidecar pods that can include any valid configuration for the
  # configured proxy.
#  proxyDefaults: |
#    {
#      "envoy_extra_static_clusters_json": "{\"connect_timeout\": \"3.000s\", \"dns_lookup_family\": \"V4_ONLY\", \"lb_policy\": \"ROUND_ROBIN\", \"load_assignment\": { \"cluster_name\": \"jaeger_9411\", \"endpoints\": [ { \"lb_endpoints\": [ { \"endpoint\": { \"address\": { \"socket_address\": { \"address\": \"jaeger\", \"port_value\": 9411, \"protocol\": \"TCP\" } } } } ] } ] }, \"name\": \"jaeger_9411\", \"type\": \"STRICT_DNS\" }",
#      "envoy_tracing_json":"{ \"http\": { \"config\": { \"collector_cluster\": \"jaeger_9411\", \"collector_endpoint\": \"/api/v1/spans\" }, \"name\": \"envoy.zipkin\" }}"
#    }