collector:
  enabled: true
  annotations: {}
  image: jaegertracing/jaeger-collector
  # tag: 1.22
  imagePullSecrets: []
  pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    grpc:
      port: 14250
      # nodePort:
    # httpPort: can accept spans directly from clients in jaeger.thrift format
    #http:
      #port: 14268
      # nodePort:
    # can accept Zipkin spans in JSON or Thrift
    zipkin: 
      port: 9411
      # nodePort:
    #otlp:
      #grpc: {}
        # nodePort:
      #http: {}
        # port: 4318
        # nodePort:
  ingress:
    enabled: false
  serviceAccount:
    create: true
    # Explicitly mounts the API credentials for the Service Account
    automountServiceAccountToken: false

query:
  enabled: true
  agentSidecar:
    enabled: true
  annotations: {}
  image: jaegertracing/jaeger-query
  # tag: 1.22
  imagePullSecrets: []
  pullPolicy: IfNotPresent
  service:
    annotations: {}
    type: ClusterIP
    # List of IP ranges that are allowed to access the load balancer (if supported)
    loadBalancerSourceRanges: []
    port: 80
    # Specify a custom target port (e.g. port of auth proxy)
    # targetPort: 8080
    # Specify a specific node port when type is NodePort
    # nodePort: 32500
  ingress:
    enabled: false
  serviceAccount:
    create: true
    # Explicitly mounts the API credentials for the Service Account
    automountServiceAccountToken: false

provisionDataStore:
  cassandra: false
storage:
  type: memory