apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
metadata:
  name: sidecar-for-my-app
spec:
  mode: sidecar
  config: |
    receivers:
      jaeger:
        protocols:
          grpc:
          thrift_binary:
          thrift_compact:
          thrift_http:
    exporters:
      logging:
      jaeger:
        endpoint: "simplest-collector.default.svc.cluster.local:14250"
        tls:
          insecure: true
    processors:
    service:
      pipelines:
        traces:
          receivers: [jaeger]
          processors: []
          exporters: [logging,jaeger]